web_cofres/apps/home/urls.py
from django.conf.urls.defaults import patterns, url


urlpatterns = patterns('web_cofres.apps.home.views',
	url(r'^$', 'index_view' , name = 'vista_index'),
	url(r'^contacto/$', 'contacto_view' , name = 'vista_contacto'),
	url(r'^lista_slider/(?P<bandera>.*)/$', 'lista_slider_view' , name = 'vista_slider'),
	url(r'^slider/(?P<id_carousel>.*)/$', 'slider_view' , name = 'vista_slider'),
	url(r'^sabias/$', 'sabias_que_view' , name = 'vista_sabias'),
	url(r'^nosotros/$', 'sobre_nosotros_view' , name = 'vista_nosotros'),
	url(r'^productos/page/(?P<pagina>.*)/$', 'productos_view' , name = 'vista_productos'),
	url(r'^login/$', 'login_view', name = 'vista_login'),
	url(r'^logout/$', 'logout_view', name = 'vista_logout'),
)

web_cofres/apps/productos/urls.py
from django.conf.urls.defaults import patterns, url


urlpatterns = patterns('web_cofres.apps.productos.views',
	url(r'^add/product/$','add_producto_view', name = 'vista_agregar_producto'),
	url(r'^add/sabias/$','add_sabias_view', name = 'vista_agregar_sabias'),
	url(r'^edit/product/(?P<id_producto>.*)/$', 'edit_producto_view' , name = 'vista_editar_productos'),
	url(r'^add/slider/$','add_slider_view', name = 'vista_agregar_slider'),
	url(r'^edit/slider/(?P<id_slider>.*)/$', 'edit_slider_view' , name = 'vista_editar_slider'),
	url(r'^activar/slider/(?P<id_item>.*)/$', 'activar_item_view' , name = 'vista_activar_slider'),
	url(r'^desactivar/slider/(?P<id_item>.*)/$', 'desactivar_item_view' , name = 'desactivar_activar_slider'),
	url(r'^edit/carousel/(?P<id_carousel>.*)/$','edit_carousel_view', name = 'vista_editar_carousel'),
)

web_cofres/urls.py
from django.conf.urls import patterns, include, url
import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'web_cofres.views.home', name='home'),
    # url(r'^web_cofres/', include('web_cofres.foo.urls')),
	url(r'^',include('web_cofres.apps.home.urls')),
	url(r'^',include('web_cofres.apps.productos.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
	url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
	url(r'^admin/', include(admin.site.urls)),
	url(r'^media/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.MEDIA_ROOT}),
)

web_cofres/apps/home/models.py
from django.db import models

# Create your models here.

web_cofres/apps/productos/models.py
from django.db import models

# Create your models here.

class Slider(models.Model):

	def url(self,filename):
		ruta = "MultimediaData/Slider/%s_%s"%(self.Nombre, str(filename))
		return ruta
	Nombre 		= models.CharField(max_length = 50)
	Imagen		= models.ImageField(upload_to = url)
	Estado		= models.BooleanField(default = True)

	def __unicode__(self):
		return self.Nombre

class Carousel(models.Model):

	def url(self,filename):
		ruta = "MultimediaData/Carousel/%s_%s"%(self.Nombre, str(filename))
		return ruta
	Nombre 		= models.CharField(max_length = 50)
	Imagen_1	= models.ImageField(upload_to = url)
	Imagen_2	= models.ImageField(upload_to = url)
	Imagen_3	= models.ImageField(upload_to = url)
	Imagen_4	= models.ImageField(upload_to = url)	
	Imagen_5	= models.ImageField(upload_to = url)
	Descripcion	= models.TextField(max_length = 200)
	Estado		= models.BooleanField(default = True)


	def __unicode__(self):
		return self.Nombre

class Producto(models.Model):

	def url(self,filename):
		ruta = "MultimediaData/Producto/%s_%s"%(self.Nombre, str(filename))
		return ruta

	Nombre 		= models.CharField(max_length = 50)
	Imagen		= models.ImageField(upload_to = url)
	Descripcion	= models.TextField(max_length = 500)

	def __unicode__(self):
		return self.Nombre

web_cofres/apps/home/forms.py
from django import forms


class contact_form(forms.Form):

	name  		= forms.CharField( widget = forms.TextInput())
	phone		= forms.CharField( widget = forms.TextInput())
	email		= forms.EmailField( widget = forms.TextInput())
	asunto 		=  forms.CharField( widget = forms.TextInput())
	mensaje 	= forms.CharField( widget = forms.Textarea())

class Login_form(forms.Form):
	usuario		= forms.CharField(widget = forms.TextInput())
	clave		= forms.CharField(widget = forms.PasswordInput(render_value = True))

web_cofres/apps/productos/forms.py
from django import forms
from web_cofres.apps.productos.models import *

class add_product_form(forms.ModelForm):
	class Meta:
		model   = Producto
		

class sabias_form(forms.ModelForm):
	class Meta:
		model   = Carousel
		exclude = ('Estado')

class slider_form(forms.ModelForm):
	class Meta:
		model   = Slider
		exclude = ('Estado')

web_cofres/apps/home/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponseRedirect
from web_cofres.apps.productos.models import *
from django.contrib.auth import login, logout, authenticate
from web_cofres.apps.home.forms import *
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from django.core.mail import EmailMultiAlternatives

def index_view(request):

	slider = Slider.objects.filter(Estado = True)
	ctx = {'slider':slider}
	return render_to_response('home/index.html', ctx,context_instance = RequestContext(request))

def lista_slider_view(request,bandera):
	if bandera == "Activo":
		slider = Slider.objects.filter(Estado = True)
	else:
		slider = Slider.objects.filter(Estado = False)
	ctx = {'sliders':slider,'ban':bandera}
	return render_to_response('home/lista_slider.html', ctx,context_instance = RequestContext(request))

def sobre_nosotros_view(request):
	return render_to_response('home/nosotros.html', context_instance = RequestContext(request))

def slider_view(request, id_carousel):
	carousel = Carousel.objects.get(id = id_carousel)
	ctx = {'carousel':carousel}
	return render_to_response('home/slider.html',ctx, context_instance = RequestContext(request))


def sabias_que_view(request):
	carousel = Carousel.objects.filter(Estado = True)
	ctx = {'carousel': carousel}
	return render_to_response('home/sabias.html',  ctx, context_instance = RequestContext(request))


def productos_view(request, pagina):

	productos = Producto.objects.all().order_by('Nombre')
	paginator = Paginator(productos, 4)
	try:
		page = int(pagina)
	except:
		page = 1
	try:
		productos = paginator.page(page)
	except (EmptyPage, InvalidPage):
		productos = paginator.page(paginator.num_pages)
		
	ctx = {'productos':productos}
	return render_to_response('home/productos.html', ctx, context_instance = RequestContext(request))

def contacto_view(request):

	
	if request.method == "POST":
		formulario = contact_form(request.POST)
		
		if formulario.is_valid():

			name 	= formulario.cleaned_data['name']
			email 	= formulario.cleaned_data['email']
			phone	= formulario.cleaned_data['phone']
			asunto 	= formulario.cleaned_data['asunto']
			mensaje	= formulario.cleaned_data['mensaje']

			to_admin = "cofresdelquindio@gmail.com"
			html_content = "<h5> Informacion recivida de <p>%s</p> </h5><h5> correo <p>%s</p> </h5><h5> Telefono <p>%s</p> </h5><h5>Asunto <p>%s</p> </h5> <h5> Mensaje</h5> <p> %s</p>"%(name, email, phone, asunto, mensaje)
 			msg = EmailMultiAlternatives('Mensaje Pagina Web', html_content, 'from@server.com', [to_admin])
 			msg.attach_alternative(html_content, 'text/html')
			msg.send()
			formulario = contact_form()	
			ctx = {'form':formulario, 'men':"Mensaje envia exitosamente te responderemos lo mas pronto posible"}
			return render_to_response('home/contacto.html',ctx,context_instance = RequestContext(request))
		else:
			formulario = contact_form()	
			ctx = {'form':formulario, 'men':"Por favor completa todos los campos correctamente"}
			return render_to_response('home/contacto.html',ctx,context_instance = RequestContext(request))	
	else:
		formulario = contact_form()	
	ctx = {'form':formulario}
	return render_to_response('home/contacto.html',ctx,context_instance = RequestContext(request))

def login_view(request):
	mensaje = ""
	if request.user.is_authenticated():
		return HttpResponseRedirect('/')
	else:
		if request.method == "POST":
			formulario = Login_form(request.POST)
			if formulario.is_valid():
				usu = formulario.cleaned_data['usuario']
				pas = formulario.cleaned_data['clave']
				usuario = authenticate(username = usu, password = pas)
				if usuario is not None and usuario.is_active:
					login(request, usuario)
					return HttpResponseRedirect('/')
				else:
					mensaje = "usuario y/o clave incorrecta"
		formulario = Login_form()
		ctx = {'form': formulario, 'men': mensaje}
		return render_to_response('home/login.html', ctx, context_instance = RequestContext(request))

def logout_view(request):
	logout(request)
	return HttpResponseRedirect('/')

web_cofres/apps/productos/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from web_cofres.apps.productos.forms import *
from web_cofres.apps.productos.models import *
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User

def add_producto_view(request):
	if request.method=="POST":
		formulario = add_product_form(request.POST, request.FILES) 
		if formulario.is_valid():
			add = formulario.save(commit = False)
			add.save()
			return HttpResponseRedirect ('/productos/page/1')
	else:
		formulario = add_product_form()
	ctx = {'form':formulario}
	return render_to_response('productos/add_producto.html',ctx,context_instance = RequestContext(request))

def edit_producto_view(request, id_producto):
	producto = Producto.objects.get(id = id_producto)
	if request.method == "POST":
		formulario = add_product_form(request.POST, request.FILES,instance = producto)
		if formulario.is_valid():
			edit = formulario.save(commit = False)
			edit.save()
			return HttpResponseRedirect ('/productos/page/1')
	else:
		formulario = add_product_form(instance = producto)
	bandera = "editar"
	ctx = {'form':formulario,'ban':bandera}
	return render_to_response('productos/add_producto.html', ctx , context_instance = RequestContext(request))

def edit_carousel_view(request, id_carousel):
	carousel = Carousel.objects.get(id = id_carousel)
	if request.method == "POST":
		formulario = sabias_form(request.POST, request.FILES, instance = carousel)
		if formulario.is_valid():
			edit = formulario.save(commit = False)
			edit.save()
			return HttpResponseRedirect ("/sabias")
	else:
		formulario = sabias_form(instance = carousel)
	ctx = {'form':formulario}
	return render_to_response('productos/edit_carousel.html', ctx , context_instance = RequestContext(request))


def add_slider_view(request):

	if request.method=="POST":
		formulario = slider_form(request.POST, request.FILES) 
		if formulario.is_valid():
			add = formulario.save(commit = False)
			add.save()
			return HttpResponseRedirect ('/lista_slider/Activo')
	else:
		formulario = add_product_form()
	ctx = {'form':formulario}
	return render_to_response('productos/add_edit_slider.html',ctx,context_instance = RequestContext(request))

def edit_slider_view(request, id_slider):
	slider = Slider.objects.get(id = id_slider)
	if request.method == "POST":
		formulario = slider_form(request.POST, request.FILES,instance = slider)
		if formulario.is_valid():
			edit = formulario.save(commit = False)
			edit.save()
			return HttpResponseRedirect ('/lista_slider/Activo')
	else:
		formulario = add_product_form(instance = slider)
	bandera = "editar"
	ctx = {'form':formulario,'ban':bandera}
	return render_to_response('productos/add_edit_slider.html', ctx , context_instance = RequestContext(request))

def activar_item_view(request, id_item):
	if User.is_authenticated:
		item = Slider.objects.get(id = id_item)
		item.Estado = True
		item.save()
	return HttpResponseRedirect ('/lista_slider/Inactivo')

def desactivar_item_view(request, id_item):
	if User.is_authenticated:
		item = Slider.objects.get(id = id_item)
		item.Estado = False
		item.save()
	return HttpResponseRedirect ('/lista_slider/Activo')

def add_sabias_view(request):

	if request.method=="POST":
		formulario = sabias_form(request.POST, request.FILES) 
		if formulario.is_valid():
			add = formulario.save(commit = False)
			add.save()
			return HttpResponseRedirect ('/sabias/')
	else:
		formulario = sabias_form()
	ctx = {'form':formulario}
	return render_to_response('productos/add_sabias.html',ctx,context_instance = RequestContext(request))

web_cofres/templates/home/contacto.html
{% extends 'base.html' %}
{% block title %}
	Cofres del quindio - Contacto
{% endblock %}

{% block content %}
	<div class="row">
		<h4 align="center" class="titulo">Contactanos</h4>
		<form class="col s12 m8" method="POST">	
			{%csrf_token%}	
			<div ><p>En el siguiente formulario puedes enviarnos tus comentarios y te responderemos en el menor tiempo posible. Muchas gracias por compartir con nosotros…</p></div>
			{% for field in form %}
				{% if field.name  = "name" %}
					<div class="input-field col s12 ">
						<i class="material-icons prefix">account_circle</i>
						<input type="text" name="name" id="id_name">
						<label for="id_name">Nombre</label>
					</div>
				{% endif %}
				{% if field.name  = "email" %}
					<div class="input-field col s12 ">
						<i class="material-icons prefix">email</i>
						<input type="text" name="email" id="id_email">
						<label for="id_email" data-error="wrong" data-success="right">Correo</label>
					</div>
				{% endif %}
				{% if field.name  = "phone" %}
					<div class="input-field col s12 ">
						<i class="material-icons prefix">phone</i>
						<input  type="text" name="phone" id="id_phone" >
						<label for="id_phone" data-error="wrong" data-success="right">Teléfono</label>
					</div>
				{% endif %}
				{% if field.name  = "asunto" %}
					<div class="input-field col s12 ">
						<i class="material-icons prefix">subject</i>
						<input  type="text" name="asunto" id="id_asunto" >
						<label for="id_asunto">Asunto</label>
					</div>
				{% endif %}
				{% if field.name  = "mensaje" %}
					<div class="input-field col s12 ">			
						<i class="material-icons prefix">comment</i>
						<textarea class="materialize-textarea" id="id_mensaje"name = "mensaje"></textarea>
						<label for="id_mensaje">Mensaje</label>
					</div>
				{% endif %}
			{% endfor %}
			<h6 align="center" class="titulo"><b>{{men}}</b></h6>
			<br>
			<div align="center">
				<button class="btn waves-effect waves-light" type="submit" ><b>Enviar</b><i class="material-icons right">note_add</i></button>
				<button class="btn waves-effect waves-light" type="reset" ><b>Limpiar</b><i class="material-icons right">loop</i></button>
			</div>
		</form>
		<div class="col s12 m3 push-m1 contacto">
			<div align="center"><img src="/media/images/logo.jpg" width="80%" class="responsive-img "></div>
			<div>
				<p><b class="titulo"><i class="material-icons left">contact_phone</i>Telefonos:</b></p>
				<p>315 282 3456 - 316 825 7108</p>
			</div>
			<div>
				<p class="titulo"><i class="material-icons left">textsms</i><a href="https://www.facebook.com/cofres.quindio?fref=ts" target="_blank"><img src="/media/images/logo_facebook.png"></a></p>
			</div>
			<div>
				<p><b class="titulo"><i class="material-icons left">room</i>Direccion:</b></p>
				<p>Calle 32 No. 23-32 B/Popular</p>
				<p>Armenia - Quindio</p>
				<a href="https://www.google.com.co/maps/@4.5301666,-75.6841185,3a,75y,21.49h,75.67t/data=!3m6!1e1!3m4!1s_QYEIMZwXJ3G_1PQkMthVQ!2e0!7i13312!8i6656" target="_blank">Ver Ubicacion</a>
			</div>
			<div>
				<p><b class="titulo"><i class="material-icons left">mail</i>Correos</b></p>
				<p>pacho-agudelo@hotmail.com</p>
				<p>cofresdelquindio@gmail.com</p>
				
			</div>
		</div>
	</div>

{% endblock %}

web_cofres/templates/home/index.html
{% extends 'base.html' %}

{% block title %}
	Inicio
{% endblock %}

{% block content %}
	<br>
	<div class="row z-depth-1">
		<div class="slider slider_res">
			<ul class="slides"> 
				{% for p in slider %}
					<li>
						<img src="/media/{{p.Imagen}}"> <!-- random image -->        
						<span class="span">{{p.Nombre}}</span>
					</li>
				{% endfor %}
			</ul>
			
		</div>
		{% if user.is_authenticated %}
			<a href="lista_slider/Activo">Listar items</a>
		{% endif %}
	</div>
	<br>
	<div class="row z-depth-2">
		<div class="col s12 m4">
			<div class="center promo promo-example">
				<i class="material-icons large">phone</i>
				<p class="promo-caption">Telefonos</p>
				<p class="light center">315 282 3456</p>
				<p class="light center">316 825 7108</p>
		    </div>
		</div>
		<div class="col s12 m4">
		  <div class="center promo promo-example">
				<i class="material-icons large">mail</i>
				<p class="promo-caption">Corre de contanto</p>
				<p class="light center">pacho-agudelo@hotmail.com</p>
				<p class="light center">cofresdelquindio@gmail.com</p>

		    </div>
		</div>
		<div class="col s12 m4">
		    <div class="center promo promo-example">
				<i class="material-icons large">room</i>
				<p class="promo-caption">Ubicacion</p>
				<p class="light center">Calle 32 No. 23-32 B/Popular Armenia - Quindio</p>
				<p class="light center"><a href="https://www.google.com.co/maps/@4.5301666,-75.6841185,3a,75y,21.49h,75.67t/data=!3m6!1e1!3m4!1s_QYEIMZwXJ3G_1PQkMthVQ!2e0!7i13312!8i6656" target="_blank">Ubicacion</a></p>
		    </div>
		</div>
	</div>
	
	
	  
{% endblock %}

web_cofres/templates/home/lista_slider.html
{%extends 'base.html' %}

{% block title %}
	{%if ban == "Activo" %}
		Lista de items activos
	{% else %}
		Lista de items inactivos
	{% endif %}
{% endblock %}

{% block content %}
	{%if user.is_authenticated %}
		{%if ban == "Activo" %}
			<h5 class="titulo" align="center">Lista de items activos</h5>
		{% else %}
			<h5 class="titulo" align="center">Lista de items inactivos</h5>
		{% endif %}
		<div class="row">
			<div class="col s12 m5">
				<a href="/add/slider">Agregar item</a>
			</div>
			<div class="col s12 m5">
				{% if ban == "Activo" %}
					<a href="/lista_slider/Inactivo">Listar items inactivos</a>
				{% else %}
					<a href="/lista_slider/Activo">Listar items Activos</a>
				{% endif %}
				
			</div>
		</div>
		<div class="row">
			{% for p in sliders %}
				<div class="col s12 m4">
					<h6>{{p.Nombre}}</h6>
					<img src="/media/{{p.Imagen}}" class="img_lista_slider">
					<a href="/edit/slider/{{p.id}}">Editar</a>
					{% if ban == "Activo" %}
						<a href="/desactivar/slider/{{p.id}}">Desactivar</a>
					{% else %}
						<a href="/activar/slider/{{p.id}}">activar</a>
					{% endif %}
				</div>
			{% endfor %}
		</div>
	{% else %}
		<h5 class="titulo" align="center">Debes estar autenticado para poder ver el contenido</h5>
	{% endif %}
{% endblock %}

web_cofres/templates/home/login.html
{% extends 'base.html' %}
{% block title %}
	Iniciar sesion
{% endblock %}

{% block content %}
	
	<div class="row">
		<div align="center">
			<h3>Inicio de sesion</h3>
			<form action="." method="POST" >  		
				{% csrf_token %}
				{{form.as_p}}
				{% if men %}
					{{men}}
					<br>
					<br>
				{% endif %}
				<button class="btn waves-effect waves-light" type="submit" ><b>Iniciar</b><i class="material-icons right">supervisor_account</i></button>		
				<button class="btn waves-effect waves-light" type="reset" ><b>Limpiar</b><i class="material-icons right">loop</i></button>					
				<br>
				<br>
			</form>
		</div>
	</div>
{% endblock %}

web_cofres/templates/home/nosotros.html
{% extends 'base.html' %}

{% block title %}
	Sobre nosotros
{% endblock %}

{% block content %}
	
	<br>
	<div class="row">
		<h4 align="center" class="titulo">Sobre nosotros</h4>
		<div class="col s12 m6 ">
			<ul class="collapsible popout active" data-collapsible="accordion">
				<li>
			     	<div class="collapsible-header active titulo_tarjeta"><i class="material-icons">turned_in</i>Misión</div>
			      	<div class="collapsible-body"><p>Fabricar cofres funebres de alta calidad, pensando en el medio ambiente, lo que permitirá crear un equilibrio con la naturaleza tomando un sentido de respeto hacia ella, inculcando en la conservación de nuestros bosques e innovando con nuestros modelos en el sector empleando tecnología de última generación.</p></div>
		    	</li>
	    	</ul>
	    	<ul class="collapsible popout" data-collapsible="accordion">
				<li>
			     	<div class="collapsible-header titulo_tarjeta"><i class="material-icons">work</i>Politicas</div>
			      	<div class="collapsible-body"><p>Cumplir con los estándares de claidad, con el profesionalismo de nuestro equipo de trabajo, estableciendo avances para el mejoramiento continuo de nuestros productos, buscando la exelencia y el desarrollo de nuestra empresa, comprometidos cada día con ser una entidad totalmente ecoógica, fabricando con materiales alternativos teniendo en cuenta la infraestructura de los parques cemeterios, esto lo hemos logrado gracias a la alta tecnología empleanda en nuestros productos, aboliendo las formas tipicas de puntilla y vidrio reemplazandolas por acetatos, clavillos y pegantes especiales, es de esta manera que avanzamos como empresa y nos fortalecemos cada vez mas en el sector.</p></div>
		    	</li>
	    	</ul>
    	</div>
    	<div class="col s12 m6 ">
			<ul class="collapsible popout active" data-collapsible="accordion">
				<li>
			     	<div class="collapsible-header active titulo_tarjeta"><i class="material-icons">filter_drama</i>Visión</div>
			      	<div class="collapsible-body"><p>Ser la empresa líder y reconocida a nivel nacional como innovadora aplicando estándares de alta calidad en la fabricación de cofres fúnebres ecológicos. <br><br><br></p></div>
		    	</li>
	    	</ul>
	    	<ul class="collapsible popout " data-collapsible="accordion">
				<li>
			     	<div class="collapsible-header titulo_tarjeta"><i class="material-icons">thumbs_up_down</i>Valores corporativos</div>
			      	<div class="collapsible-body">
			      		<p>
			      			Responsabilidad <br> Transparencia <br> Vocacion de servicio <br>
			      			Confianza <br> Trabajo en equipo <br> Solidaridad <br> Eficiencia <br> Honestidad <br> Compromiso <br><br> 
			      		</p>
				      	
			      	</div>
		    	</li>
	    	</ul>
	    </div>
	    <div class="col s12 m6 offset-m3">
			<ul class="collapsible popout active" data-collapsible="accordion">
				<li>
			     	<div class="collapsible-header titulo_tarjeta"><i class="material-icons">perm_identity</i>Organizacion</div>
			      	<div class="collapsible-body"><p><b>Retroalimentacion</b>
						La empresa cuenta con dos tipos de retroalimentacion:
						1. Retroalimentación empresa cliente: Aqui contamos con encuestas donde nos enteramos de la calidad del producto, cuanto le estamos afectando al medio ambiente o al entorno donde fabricamos. <br>
						2. Retroalimentación interna: La empresa no solo da espacio a sus clientes para ayudar a mejorar la empresa, tambien con cada seccion de procesos hace una consulta sobre la materia prima y la maquinaria utilizada y enterarse de que cambiar o mejorar para un buen servicio con calidad. <br>
						<b>Evaluacion</b>
						En la evalucion de de nuestra empresa, analizamos el tiempo de cada proceso, y la maquinaria utilizada, como tambien tenemos en cuenta la calidad de cada uno de nuestros productos como la resistencia, la firmeza y cada dealle de la pintura y tapizados, observamos el tiempo de entrega, sin olvidarnos de cada empleado en como ejerce su labor detalladamente. <br>
						<b>Control</b>
						El proceso de control de la empresa consiste en tener un buen seguimiento de la funcionalidad de las maquinas, tiempo de procesos y desempeño de cada empleado, teniendo todo lo evaluado en orden, al cumplir con un buen control tendremos mejores soluciones para cualquier imprevisto fuera de lo normal observado en el proceso de evaluación.</p>

					</div>
		    	</li>
	    	</ul>
	    	<br>
	</div>

{% endblock %}

web_cofres/templates/home/productos.html
{% extends 'base.html' %}
{% block title %}
	Productos
{% endblock %}

{% block content %}
	<h4 class="titulo" align="center">Nuestros Productos</h4>
	{% if user.is_authenticated%}
		<div class="col s12 m6">
			<a href="{% url 'vista_agregar_producto' %}">Nuevo Producto</a>
		</div>
	{% endif %}
	<div class="row">
		{% for p in productos%}
			<div class="col s12 m6">
				<img src="/media/{{p.Imagen}}" class="img responsive-img materialboxed"
				data-caption="{{p.Descripcion}}">
				{% if user.is_authenticated %}
					<a href="/edit/product/{{p.id}}">Editar</a>
				{% endif %}
			</div>
		{% endfor %}
		
	</div>
	<div class="row center col s12">
		<ul class="pagination">
		    {% if productos.has_previous %}
		    	<li class="active"><a href="/productos/page/{{productos.previous_page_number}}"><i class="material-icons left">chevron_left</i>Anterior</a></li>
		    {% else %}
		    	<li class="disabled"><a ><i class="material-icons left">chevron_left</i>Anterior</a></li>
			{% endif%}
			{% if productos.has_next %}
			   	<li class="active"><a href="/productos/page/{{productos.next_page_number}}">Siguiente<i class="material-icons right">chevron_right</i></a></li>
		    {% else %}			    	
				<li class="disabled"><a >Siguiente<i class="material-icons right">chevron_right</i></a></li>
		    {% endif %}	
		</ul>
			
	</div>		

{% endblock%}

web_cofres/templates/home/sabias.html
{% extends 'base.html' %}

{% block title  %}
	Sabias Que...
{% endblock %}

{% block content %}
	<div class="row">
		{% if user.is_authenticated %}
			<h6 align="center"><a href="/add/sabias/">Nuevo</a></h6>
		{% endif%}
		{% for p in carousel %}		
			<div class="col s12 m6 ">
				<h6 class="titulo_carousel"><i class="material-icons left">perm_media</i>{{p.Nombre}}</h6>
				<div class="carousel ">		
					<a class="carousel-item" ><img src="/media/{{p.Imagen_1}}" class="img_carousel"></a>
					<a class="carousel-item" ><img src="/media/{{p.Imagen_2}}" class="img_carousel"></a>
					<a class="carousel-item" ><img src="/media/{{p.Imagen_3}}" class="img_carousel"></a>
					<a class="carousel-item" ><img src="/media/{{p.Imagen_4}}" class="img_carousel"></a>
					<a class="carousel-item" ><img src="/media/{{p.Imagen_5}}" class="img_carousel"></a>
				</div>
				<p>{{p.Descripcion}} </p>
				{% if user.is_authenticated %}
					<a href="/edit/carousel/{{p.id}}">Editar</a>
				{% endif %}
			</div>
		{% endfor %}

	</div>
{% endblock %}